name: 'Dockerize'
description: 'Build and push docker image to GCP'
inputs:
  service-account-key:
    description: 'GCP service account key'
    required: true
runs:
  using: 'composite'
  steps:
  - name: Setup Cloud SDK
    uses: google-github-actions/setup-gcloud@v0.2.0
    with:
      project_id: jbaumgartner-project1
      service_account_key: ${{ inputs.service-account-key }}
      export_default_credentials: true
  - name: Authorize Docker
    shell: bash
    run: gcloud auth configure-docker
  - name: Build and Push Container
    shell: bash
    run: |-
      docker build -t gcr.io/jbaumgartner-project1/band-service:${{  github.sha }} -t gcr.io/jbaumgartner-project1/band-service:latest .
      docker push gcr.io/jbaumgartner-project1/band-service --all-tags
