name: 'Setup GCP'
description: 'Setup GCP credentials and environment'
inputs:
  service-account-key:
    description: 'GCP service account key'
    required: true
runs:
  using: 'composite'
  steps:
  - name: Setup Cloud SDK
    uses: google-github-actions/setup-gcloud@v0.2.0
    with:
      project_id: jbaumgartner-project1
      service_account_key: ${{ inputs.service-account-key }}
      export_default_credentials: true
