name: 'Deploy'
description: 'Deploy to GCP using Cloud Run service'
inputs:
  service-account-key:
    description: 'GCP service account key'
    required: true
  environment:
    description: 'Target deploy environment'
    required: true
  image-tag:
    description: 'Image tag to target in jbaumgartner-project/band-service registry'
    required: false
    default: ${{  github.sha }}
runs:
  using: 'composite'
  steps:
  - name: Setup Cloud SDK
    uses: google-github-actions/setup-gcloud@v0.2.0
    with:
      project_id: jbaumgartner-project1
      service_account_key: ${{ inputs.service-account-key }}
      export_default_credentials: true
  - name: Deploy to Cloud Run
    id: deploy
    uses: google-github-actions/deploy-cloudrun@v0.4.0
    with:
      service: band-service-${{ inputs.environment }}
      image: gcr.io/jbaumgartner-project1/band-service:${{ inputs.image-tag }}
      region: us-central1
