name: Dev Deploy
on:
  push:
    branches: [ 'dev-deploy/**' ]
  schedule:
  - cron: '0 8 * * 1-5'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Java
      uses: ./.github/actions/setup-java
    - name: Build
      run: ./gradlew bootJar
    - name: Upload Jar Artifacts
      uses: actions/upload-artifact@v2.2.4
      with:
        name: App Jar
        path: build/libs/**

  dev-deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: development
    steps:
    - name: Download Jar
      uses: actions/download-artifact@v2.0.10
      with:
        name: App Jar
        path: artifacts/
    - name: Dockerize App
      run: echo "Dockerizing..."
    - name: Deploy to Development
      run: echo "Deploying to dev environment..."
    - name: Smoke Tests
      run: echo "Run smoke tests..."
