name: Dev Deploy
on:
  push:
    branches: [ 'dev-deploy/**' ]
  schedule:
  - cron: '0 8 * * 1-5'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Java
      uses: ./.github/actions/setup-java
    - name: Build
      run: ./gradlew bootJar
    - name: Upload Jar Artifacts
      uses: actions/upload-artifact@v2.2.4
      with:
        name: App Jar
        path: build/libs/**

  dockerize:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup GCP
        uses: ./.github/actions/setup-gcp
      - name: Download Jar
        uses: actions/download-artifact@v2.0.10
        with:
          name: App Jar
          path: build/libs/
      - name: Build & Publish Docker Image to GCP
        uses: ./.github/actions/dockerize

  dev-deploy:
    runs-on: ubuntu-latest
    needs: dockerize
    environment: development
    steps:
    - name: Deploy to Cloud Run
      uses: ./.github/actions/deploy
      with:
        environment: development
    - name: Smoke Tests
      run: echo "Run smoke tests..."
