name: Push to main
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Java
      uses: ./.github/actions/setup-java
    - name: Build
      run: ./gradlew bootJar
    - name: Upload Jar Artifacts
      uses: actions/upload-artifact@v2.2.4
      with:
        name: App Jar
        path: build/libs/**

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Java
      uses: ./.github/actions/setup-java
    - name: Lint & Test
      run: ./gradlew check
    - name: Check Code Coverage
      run: ./gradlew jacocoTestCoverageVerification jacocoTestReport
    - name: Upload Test Reports Artifacts
      uses: actions/upload-artifact@v2.2.4
      if: always()
      with:
        name: Test Reports
        path: build/reports/**

  dockerize:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Download Jar
      uses: actions/download-artifact@v2.0.10
      with:
        name: App Jar
        path: build/libs/
    - name: Build & Publish Docker Image to GCP
      uses: ./.github/actions/dockerize
      with:
        service-account-key: ${{ secrets.GCP_SA_KEY }}

  staging-deploy:
    runs-on: ubuntu-latest
    needs: [test, dockerize]
    environment: staging
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Deploy to Cloud Run
      uses: ./.github/actions/deploy
      with:
        service-account-key: ${{ secrets.GCP_SA_KEY }}
        environment: staging
    - name: Smoke Tests
      run: echo "Run smoke tests..."

  production-deploy:
    runs-on: ubuntu-latest
    needs: staging-deploy
    environment: production
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Deploy to Cloud Run
      uses: ./.github/actions/deploy
      with:
        service-account-key: ${{ secrets.GCP_SA_KEY }}
        environment: production
    - name: Smoke Tests
      run: echo "Run smoke tests..."
