name: Pull Requests to main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Environment
      uses: ./.github/actions/setup
    - name: Build
      uses: ./.github/actions/build
    - name: Test
      uses: ./.github/actions/test
