name: Pull Request to main
on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Java
      uses: ./.github/actions/setup-java
    - name: Build
      run: ./gradlew bootJar
    - name: Upload Jar Artifacts
      uses: actions/upload-artifact@v2.2.4
      with:
        name: App Jar
        path: build/libs/**

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Java
      uses: ./.github/actions/setup-java
    - name: Lint & Test
      run: ./gradlew check
    - name: Check Code Coverage
      run: ./gradlew jacocoTestCoverageVerification jacocoTestReport
    - name: Upload Test Reports Artifacts
      uses: actions/upload-artifact@v2.2.4
      if: always()
      with:
        name: Test Reports
        path: build/reports/**
