name: Pull Requests to main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - uses: ./.github/actions/setup
    - name: Build & Test Override
      uses: ./.github/actions/build-test
