name: Reset Dev Deploy
on:
  schedule:
    - cron: '0 8 * * 1-5'

jobs:
  dev-deploy:
    runs-on: ubuntu-latest
    environment: development
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Deploy to Cloud Run
      uses: ./.github/actions/deploy
      with:
        service-account-key: ${{ secrets.GCP_SA_KEY }}
        environment: development
        image-tag: latest
    - name: Smoke Tests
      run: echo "Run smoke tests..."
